### PR TITLE
Changed assignment_tag to simple_tag for Django 2.0

### PR DESCRIPTION
**Pull request by Daniel-Avila**

### CODE REVIEW

**Comment by Rekoc** [comment]
I got the same error, switch assignment_tag to simple_tag worked fine for me as well.
For more information: https://docs.djangoproject.com/en/2.1/releases/1.9/#assignment-tag

**Comment by vanessa** [comment]
Would love to see this PR merged 👍

**Comment by alexandervlpl** [comment]
@lazybird would be really great to merge this and make a new PyPI release!

**Comment by thomascenni** [comment]
@lazybird should be very useful to merge this PR !
With this simple change, you have a library working with the latest release available of Django (3.2.X).
Thanks in advance

**Comment by thomascenni** [comment]
Thanks @lazybird !

**Pull request merged**
